name: dbtsmith_output
version: "1.0.0"
config-version: 2

profile: dbtsmith_output

model-paths: ["models"]

models:
  dbtsmith_output:
    staging:
      +materialized: view
    marts:
      +materialized: table